version: '3.7'

services:
  event-publisher:
    build:
      context: ./producer
    container_name: producer
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_HOST: rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    networks:
      - app-network

  event-consumer:
    build:
      context: ./consumer
    container_name: consumer
    depends_on:
      - rabbitmq
    ports:
      - "3001:3001"
    environment:
      RABBITMQ_HOST: rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    networks:
      - app-network

  auth-service:
    build:
      context: ./authentication-service
    container_name: authentication-service
    ports:
      - "3003:3003"
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    networks:
      - app-network

  document-service:
    build:
      context: ./document-service
    container_name: document-service
    ports:
      - "3004:3004"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - event-publisher
      - event-consumer
      - user-service
      - auth-service
      - document-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge