name: Release

on:
  push:
    branches:
      - main
      - dev  # Optionally track dev branch if you use it
    tags:
      - 'v*'  # Trigger on version tags, e.g. v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.8.1

      - name: Install dependencies
        run: npm ci  # This installs all dependencies defined in package-lock.json

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token for release creation
        run: npx semantic-release